export function findIndexByColumnsNameIn2DArray(array2D, searchValue) {
  for (let i = 0; i < array2D.length; i++) {
    if (array2D[i][0] === searchValue) {
      // Found the value in the first index, return the entire sub-array
      return i;
    }
  }
  // Value not found, return null or handle it as needed
  return 0;
}

// Vertex AI Search Table Format

export const vertex_ai_search_configValues = [
  ["Config", "Value"],
  ["Vertex AI Search Project Number", "384473000457"],
  ["Vertex AI Search DataStore Name", "alphabet-pdfs_1695783402380"],
  ["Vertex AI Project ID", "argolis-arau"],
  ["Vertex AI Location", "us-central1"],
  ["maxExtractiveAnswerCount (1-5)", "2"], //maxExtractiveAnswerCount
  ["maxExtractiveSegmentCount (1-5)", "0"], //maxExtractiveSegmentCount
  ["maxSnippetCount (1-5)", "0"], //maxSnippetCount
  ["Preamble (Customized Summaries)", ""],
  ["Summarization Model", "gemini-1.0-pro-001/answer_gen/v1"],
  ["summaryResultCount (1-5)", "2"], //summaryResultCount
  ["Genrate Grounding Score", "True"], //generate grounding score
  ["useSemanticChunks (True or False)", "False"], //useSemanticChunks
  ["ignoreAdversarialQuery (True or False)", "True"], // ignoreAdversarialQuery
  ["ignoreNonSummarySeekingQuery (True or False)", "True"], // ignoreNonSummarySeekingQuery
  [
    "SummaryMatchingAdditionalPrompt",
    "If there are monetary numbers in the answers, they should be matched exactly.",
  ],
  ["Batch Size (1-10)", "5"], // BatchSize
  ["Time between Batches in Seconds (1-10)", "1"],
];

export const vertex_ai_search_testTableHeader = [
  [
    "ID",
    "Query",
    "Expected Summary",
    "Actual Summary",
    "Summary Match",
    "First Link Match",
    "Link in Top 2",
    "Grounding Score",
    "Expected Link 1",
    "Expected Link 2",
    "Expected Link 3",
    "Actual Link 1",
    "Actual Link 2",
    "Actual Link 3",
  ],
];

export var summaryMatching_prompt =
  "You will get two answers to a question, you should determine if they are semantically similar or not. ";
export var summaryMatching_examples = `examples - answer_1: I was created by X. answer_2: X created me. output:same 
  answer_1:There are 52 days in a year. answer_2: A year is fairly long. output:different `;

// Synthetic Q&A  Table Format
export const synth_q_and_a_configValues = [
  ["Config", "Value"],
  ["Vertex AI Project ID", "argolis-arau"],
  ["Vertex AI Location", "us-central1"],
  ["Gemini Model ID", "gemini-1.5-flash-001"],
  [
    "System Instructions",
    `Given the attached document, generate a question and an answer.The question should only be sourced from the provided the document. Do not use any other information other than the attached document. Explain your reasoning for the answer by quoting verbatim where in the document the answer is found. Return the results in JSON format.Example: {'question': 'Here is a question?', 'answer': 'Here is the answer', 'reasoning': 'Quote from document'}`,
  ],
  [
    "Prompt",
    `You are an expert in reading call center policy and procedure documents. Generate question and answer a customer would ask from a Bank using the attached document.`,
  ],
  ["Generate Q & A Quality", "TRUE"],
  [
    "Q & A Quality Prompt",
    `# Instruction
You are an expert evaluator. Your task is to evaluate the quality of the responses generated by AI models.
We will provide you with the user prompt and an AI-generated responses.
You should first read the user prompt carefully for analyzing the task, and then evaluate the quality of the responses based on and rules provided in the Evaluation section below.

# Evaluation
## Metric Definition
You will be assessing question answering quality, which measures the overall quality of the answer to the question in user prompt. Pay special attention to length constraints, such as in X words or in Y sentences. The instruction for performing a question-answering task is provided in the user prompt. The response should not contain information that is not present in the context (if it is provided).

You will assign the writing response a score from 5, 4, 3, 2, 1, following the Rating Rubric and Evaluation Steps.
Give step-by-step explanations for your scoring, and only choose scores from 5, 4, 3, 2, 1.

## Criteria Definition
Instruction following: The response demonstrates a clear understanding of the question answering task instructions, satisfying all of the instruction's requirements.
Groundedness: The response contains information included only in the context if the context is present in user prompt. The response does not reference any outside information.
Completeness: The response completely answers the question with suffient detail.
Fluent: The response is well-organized and easy to read.

## Rating Rubric
5: (Very good). The answer follows instructions, is grounded, complete, and fluent.
4: (Good). The answer follows instructions, is grounded, complete, but is not very fluent.
3: (Ok). The answer mostly follows instructions, is grounded, answers the question partially and is not very fluent.
2: (Bad). The answer does not follow the instructions very well, is incomplete or not fully grounded.
1: (Very bad). The answer does not follow the instructions, is wrong and not grounded.

## Evaluation Steps
STEP 1: Assess the response in aspects of instruction following, groundedness,completeness, and fluency according to the crtieria.
STEP 2: Score based on the rubric.

Return result in JSON format. example output: { 'rating': 2 , evaluation: 'reason'}`,
  ],
  ["Q & A Quality Model ID", "gemini-1.5-pro-001"],
  ["Max Concurrent Requests (1-10)", "5"],
  ["Request Interval in Seconds(1-10)", "1"],
];

export const synth_q_and_a_TableHeader = [
  ["ID", "GCS File URI", "Mime Type", "Generated Question", "Expected Answer", "Q & A Quality"],
];

// Summarization  Table Format
export const summarization_configValues = [
  ["Config", "Value"],
  ["Vertex AI Project ID", "argolis-arau"],
  ["Vertex AI Location", "us-central1"],
  ["Gemini Model ID", "gemini-1.5-flash-001"],
  ["Instructions", "Summarize the text."],
  ["summarization_quality", "TRUE"],
  ["summarization_helpfulness", "TRUE"],
  ["summarization_verbosity", "FALSE"],
  ["groundedness", "FALSE"],
  ["fulfillment", "FALSE"],
  ["Batch Size (1-10)", "4"], // BatchSize
  ["Time between Batches in Seconds (1-10)", "2"],
];

export const summarization_TableHeader = [
  [
    "ID",
    "Context",
    "Summary",
    "summarization_quality",
    "summarization_helpfulness",
    "summarization_verbosity",
    "groundedness",
    "fulfillment",
  ],
];

// Eval Maps
export const mapQuestionAnsweringScore = new Map();
mapQuestionAnsweringScore.set("1", "1-Very Bad");
mapQuestionAnsweringScore.set("2", "2-Bad");
mapQuestionAnsweringScore.set("3", "3-OK");
mapQuestionAnsweringScore.set("4", "4-Good");
mapQuestionAnsweringScore.set("5", "5-Very Good");
mapQuestionAnsweringScore.set(1, "1-Very Bad");
mapQuestionAnsweringScore.set(2, "2-Bad");
mapQuestionAnsweringScore.set(3, "3-OK");
mapQuestionAnsweringScore.set(4, "4-Good");
mapQuestionAnsweringScore.set(5, "5-Very Good");

export const mapSummaryQualityScore = new Map();
mapSummaryQualityScore.set(1, "1-Very Bad");
mapSummaryQualityScore.set(2, "2-Bad");
mapSummaryQualityScore.set(3, "3-OK");
mapSummaryQualityScore.set(4, "4-Good");
mapSummaryQualityScore.set(5, "5-Very Good");

export const mapSummaryHelpfulnessScore = new Map();
mapSummaryHelpfulnessScore.set(1, "1-Unhelpful");
mapSummaryHelpfulnessScore.set(2, "2-Somewhat Unhelpful");
mapSummaryHelpfulnessScore.set(3, "3-Neutral");
mapSummaryHelpfulnessScore.set(4, "4-Somewhat Helpful");
mapSummaryHelpfulnessScore.set(5, "5-Helpful");

export const mapSummaryVerbosityScore = new Map();
mapSummaryVerbosityScore.set(-2, "-2-Terse");
mapSummaryVerbosityScore.set(-1, "-1-Somewhat Terse");
mapSummaryVerbosityScore.set(0, "0-Optimal");
mapSummaryVerbosityScore.set(1, "1-Somewhat Verbose");
mapSummaryVerbosityScore.set(2, "2-Verbose");

export const mapTextgenGroundednessScore = new Map();
mapTextgenGroundednessScore.set(0, "0-Ungrounded");
mapTextgenGroundednessScore.set(1, "1-Grounded");

export const mapTextgenFulfillmentScore = new Map();
mapTextgenFulfillmentScore.set(1, "1-No fulfillment");
mapTextgenFulfillmentScore.set(2, "2-Poor fulfillment");
mapTextgenFulfillmentScore.set(3, "3-Some fulfillment");
mapTextgenFulfillmentScore.set(4, "4-Good fulfillment");
mapTextgenFulfillmentScore.set(5, "5-Complete fulfillmentl");

export class VertexAIError extends Error {
  constructor(id, message = "Processing Error") {
    super(message);
    this.name = "VertexAIError";
    this.id = id;
  }
}

export class NotAuthenticatedError extends Error {
  constructor(id, message = "User is not authenticated") {
    super(message);
    this.name = "NotAuthenticatedError";
    this.id = id;
    this.statusCode = 401; // Optional: HTTP status code for API errors
  }
}

export class QuotaError extends Error {
  constructor(id, message = "Quota Exceeded") {
    super(message);
    this.name = "QuotaError";
    this.id = id;
    this.statusCode = 429; // Optional: HTTP status code for API errors
  }
}

export class PermissionDeniedError extends Error {
  constructor(id, message = "Permission Denied") {
    super(message);
    this.name = "PermissionDeniedError";
    this.id = id;
    this.statusCode = 403; // Optional: HTTP status code for API errors
  }
}

export class ResourceNotFoundError extends Error {
  constructor(id, message = "Resource Not Found ") {
    super(message);
    this.name = "ResourceNotFoundError";
    this.id = id;
    this.statusCode = 404; // Optional: HTTP status code for API errors
  }
}
